import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { Oswald } from "next/font/google";
import { ReduxProvider } from "@/providers/redux-provider/ReduxProvider";
import FooterSection from "@/components/footer";

const oswald = Oswald({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={`${oswald.variable} antialiased`}>
        <ReduxProvider>
          <Header />
          {children}
          <FooterSection />
        </ReduxProvider>
      </body>
    </html>
  );
}
